trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: RunWorkflow@1
  inputs:
    gh: 'github.com_ahethaysham'
    repo: 'Ahethaysham-Ahmed/githubtf2'
    workflow: 'My Workflow'
    ref: 'main'
    dlArtifacts: true