# File: azure-pipelines.yml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'
#     architecture: 'x64'
# - script: |
#     python -m venv env
#     source env/bin/activate
#     pip install -r requirements.txt
#     pytest
#   displayName: 'Run Tests'
# - task: GitHubAction@0
#   inputs:
#     repository: 'Ahethaysham-Ahmed/githubtf2'
#     workflow: 'policyscan.yml'
#     actionInputs: |
#       scopes: '/subscriptions/your-subscription-id-here'
#     token: $(ARM_GITHUB_TOKEN)
- task: RunWorkflow@1
  inputs:
    gh: 'github.com_ahethaysham'
    repo: 'Ahethaysham-Ahmed/githubtf2'
    workflow: 'workflows/policy-scan.yml'
    ref: 'main'