name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-apply:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read # default

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Terraform Plan
        uses: MphasisPipelineFactory/shared-workflows@main
        with:
          workflow: '.github/workflows/terraform-plan.yml'

      - name: Trigger Terraform Apply
        uses: MphasisPipelineFactory/shared-workflows@main
        with:
          workflow: '.github/workflows/terraform-apply.yml'

#        uses: MphasisPipelineFactory/shared-workflows@main
