name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-apply:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # default
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  terraform-apply:
    name: 'Trigger Terraform Apply'
    needs: terraform-plan-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
    jobs1:
      call-workflow-1-in-another-repo:
        uses: MphasisPipelineFactory/shared-workflows/.github/workflows/terraform-plan.yml@main

      call-workflow-2-in-another-repo:
        uses: MphasisPipelineFactory/shared-workflows/.github/workflows/terraform-apply.yml@main


