name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-apply:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # default
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  terraform-plan:
    name: 'Trigger Terraform Plan'
    needs: terraform-plan-apply
    runs-on: ubuntu-latest
    uses: MphasisPipelineFactory/shared-workflows/.github/workflows/terraform-plan.yml@main

  terraform-apply:
    name: 'Trigger Terraform Apply'
    needs: terraform-plan
    runs-on: ubuntu-latest
    uses: MphasisPipelineFactory/shared-workflows/.github/workflows/terraform-apply.yml@main
