name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan-apply:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Trigger Terraform Plan
        uses: Ahethaysham-Ahmed/githubtf2@main

      - name: Trigger Terraform Apply
        uses: Ahethaysham-Ahmed/githubtf2@main
